/** @type {import('next').NextConfig} */

const nextConfig = {
  reactStrictMode: true,
  images: {
    domains: [process.env.RIOT_IMAGES],
  },
  env: {
    NEXT_PUBLIC_DDRAGON_API_BASE: process.env.NEXT_PUBLIC_DDRAGON_API_BASE,
    NEXT_PUBLIC_DDRAGON_API_CHAMPIONS:
      process.env.NEXT_PUBLIC_DDRAGON_API_CHAMPIONS,
    NEXT_PUBLIC_DDRAGON_API_VERSION:
      process.env.NEXT_PUBLIC_DDRAGON_API_VERSION,
    NEXT_PUBLIC_DDRAGON_API_SPLASH: process.env.NEXT_PUBLIC_DDRAGON_API_SPLASH,
    NEXT_PUBLIC_DDRAGON_API_LOADING:
      process.env.NEXT_PUBLIC_DDRAGON_API_LOADING,
    NEXT_PUBLIC_DDRAGON_API_SQUARE: process.env.NEXT_PUBLIC_DDRAGON_API_SQUARE,
    NEXT_PUBLIC_SUPABASE_ANON_KEY: process.env.NEXT_PUBLIC_SUPABASE_ANON_KEY,
    NEXT_PUBLIC_SUPABASE_URL: process.env.NEXT_PUBLIC_SUPABASE_URL,
  },
};

module.exports = nextConfig;
