const {
  NEXT_PUBLIC_DDRAGON_API_BASE: DDRAGON_API_BASE,
  NEXT_PUBLIC_DDRAGON_API_CHAMPIONS: DDRAGON_API_CHAMPIONS,
  NEXT_PUBLIC_DDRAGON_API_VERSION: DDRAGON_API_VERSION,
  NEXT_PUBLIC_DDRAGON_API_SQUARE: DDRAGON_API_SQUARE,
  NEXT_PUBLIC_DDRAGON_API_LOADING: DDRAGON_API_LOADING,
  NEXT_PUBLIC_DDRAGON_API_SPLASH: DDRAGON_API_SPLASH,
} = process?.env;

export const URL = {
  GET_CHAMPIONS: `${DDRAGON_API_BASE}${DDRAGON_API_VERSION}/${DDRAGON_API_CHAMPIONS}`,
  GET_LOADING: `${DDRAGON_API_BASE}${DDRAGON_API_LOADING}`,
  GET_SPLASH: `${DDRAGON_API_BASE}${DDRAGON_API_SPLASH}`,
  GET_SQUARE: `${DDRAGON_API_BASE}${DDRAGON_API_SQUARE}`,
};

export function getChampions() {
  return fetch(URL.GET_CHAMPIONS);
}
