export const PUBLIC_VARS = {
  DDRAGON_API_BASE: process.env.NEXT_PUBLIC_DDRAGON_API_BASE,
  DDRAGON_API_CHAMPIONS: process.env.NEXT_PUBLIC_DDRAGON_API_CHAMPIONS,
  DDRAGON_API_VERSION: process.env.NEXT_PUBLIC_DDRAGON_API_VERSION,
  DDRAGON_API_SQUARE: process.env.NEXT_PUBLIC_DDRAGON_API_SQUARE,
  DDRAGON_API_LOADING: process.env.NEXT_PUBLIC_DDRAGON_API_LOADING,
  DDRAGON_API_SPLASH: process.env.NEXT_PUBLIC_DDRAGON_API_SPLASH,
};
